#!/usr/bin/env python3
"""
Generate a candidate ranking for the demo dataset.
Usage: python scripts/generate_ranking.py [dataset_uuid] [application_target]

application_target options (default: li_ion_batteries):
  li_ion_batteries | solid_state_batteries | cathode_materials |
  anode_materials | solid_electrolytes | general_energy_storage
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import uuid
from app.infrastructure.database.session import SessionLocal
from app.infrastructure.database.repositories import DatasetRepository, UserRepository
from app.application.use_cases.rank_candidates_use_case import RankCandidatesUseCase
from app.domain.entities.candidate_ranking import RankingWeights
from app.core.constants import ApplicationTarget
from app.core.logging_config import configure_logging

configure_logging()

_TARGET_MAP = {t.value: t for t in ApplicationTarget}


def main():
    dataset_id_str = sys.argv[1] if len(sys.argv) > 1 else None
    target_str = sys.argv[2] if len(sys.argv) > 2 else "li_ion_batteries"

    if target_str not in _TARGET_MAP:
        print(
            f"ERROR: Unknown application target '{target_str}'.\n"
            f"Valid options: {list(_TARGET_MAP.keys())}"
        )
        sys.exit(1)
    application_target = _TARGET_MAP[target_str]

    with SessionLocal() as db:
        # ---- Resolve admin user ------------------------------------------
        user_repo = UserRepository(db)
        admin = user_repo.get_by_email(os.getenv("ADMIN_EMAIL", "admin@matenergy.local"))
        if not admin:
            print("Admin user not found. Run scripts/seed_db.py first.")
            sys.exit(1)

        # ---- Resolve dataset ----------------------------------------------
        ds_repo = DatasetRepository(db)
        if dataset_id_str:
            try:
                dataset = ds_repo.get_by_id(uuid.UUID(dataset_id_str))
            except ValueError:
                print(f"ERROR: Invalid UUID: {dataset_id_str!r}")
                sys.exit(1)
            if not dataset:
                print(f"Dataset {dataset_id_str} not found.")
                sys.exit(1)
        else:
            datasets = ds_repo.get_by_status("valid")
            if not datasets:
                print(
                    "No valid datasets found. "
                    "Run import_demo_data.py first."
                )
                sys.exit(1)
            dataset = datasets[0]

        print(f"Dataset           : {dataset.name} ({dataset.id})")
        print(f"Application target: {application_target.value}\n")

        # ---- Default weights (sum = 1.0) ---------------------------------
        weights = RankingWeights(
            stability_weight=0.30,
            target_property_weight=0.25,
            energy_relevance_weight=0.20,
            abundance_weight=0.10,
            toxicity_penalty_weight=0.05,
            uncertainty_penalty_weight=0.05,
            out_of_domain_penalty_weight=0.05,
        )
        assert weights.validate(), "Ranking weights do not sum to 1.0"

        # ---- Run ranking -------------------------------------------------
        use_case = RankCandidatesUseCase(db)
        try:
            result = use_case.execute(
                name=f"Demo {application_target.value} Ranking",
                application_target=application_target,
                dataset_id=dataset.id,
                user_id=admin.id,
                weights=weights,
                description=(
                    f"Baseline ranking of demo materials for {application_target.value} "
                    "applications — generated by generate_ranking.py"
                ),
            )
        except ValueError as exc:
            print(f"ERROR: {exc}")
            sys.exit(1)

        print(f"Ranking created   : {result['ranking_id']}")
        print(f"Total candidates  : {result['n_candidates']}")
        print("\nTop 5 candidates:")
        for item in result.get("top_5", []):
            print(
                f"  #{item['rank']:>3}  score={item['score']:.3f}"
                f"  priority={item['priority']:<20s}"
                f"  material_id={item['material_id']}"
            )


if __name__ == "__main__":
    main()
