"""
ScientificLimitationsService
=============================
Provides static, rule-based scientific limitation warnings for:
  - descriptor types (compositional vs structural)
  - ML model types (regression, classification, neural network, etc.)
  - individual predictions (OOD, uncalibrated, extrapolation)
  - target properties (DFT accuracy, approximations)

All text is hard-coded, not generated by AI.  These warnings are intended
to appear in reports, UI tooltips, and prediction outputs to ensure
scientific honesty as required by the thesis scope.

Reference: docs/limitations.md
"""
from __future__ import annotations

from typing import Optional


_DESCRIPTOR_LIMITATIONS: dict[str, list[str]] = {
    "compositional": [
        "Compositional descriptors encode only elemental statistics averaged over the "
        "formula stoichiometry. They contain no information about crystal structure, "
        "atomic arrangement, or bonding geometry.",
        "Two materials with the same formula but different polymorphs (e.g., α-Li2O and "
        "β-Li2O) are indistinguishable by compositional descriptors alone.",
        "Predictions based solely on compositional features are less reliable for "
        "properties that strongly depend on crystal structure, such as band gap and "
        "ionic conductivity.",
        "Extrapolation to chemical systems not represented in the training set carries "
        "higher uncertainty and should be treated as qualitative screening only.",
    ],
    "structural": [
        "Structural descriptors require a known crystal structure. Materials without "
        "an experimentally or computationally determined structure cannot be processed.",
        "DFT-relaxed structures may differ from experimentally observed structures, "
        "especially for disordered or partially occupied sites.",
        "Space-group and lattice parameter descriptors may not capture subtle local "
        "distortions that govern electrochemical properties.",
    ],
    "combined": [
        "Combined compositional + structural descriptors provide better coverage but "
        "require both a valid formula and a crystal structure for every material.",
        "Missing structural data leads to zero-imputation of structural features, "
        "which may introduce systematic bias in the feature matrix.",
    ],
}

_MODEL_LIMITATIONS: dict[str, list[str]] = {
    "ridge_regression": [
        "Ridge regression assumes a linear relationship between features and target. "
        "Non-linear property dependencies (common in materials science) may not be "
        "captured accurately.",
        "Performance degrades when the feature space contains strong non-linearities "
        "or highly correlated blocks of features.",
    ],
    "random_forest_regressor": [
        "Random forests cannot extrapolate beyond the range of the training data. "
        "Predictions for materials with properties outside the training distribution "
        "are unreliable.",
        "Feature importance from Random Forests reflects impurity reduction, not "
        "causal relationships with the target property.",
    ],
    "random_forest_classifier": [
        "Classification thresholds (e.g. energy_above_hull ≤ 0.05 eV/atom for 'stable') "
        "are configurable but arbitrary from a physical standpoint.",
        "Class imbalance in the training data can bias the classifier toward the "
        "majority class. Check balanced_accuracy alongside accuracy.",
    ],
    "gradient_boosting_regressor": [
        "Gradient Boosting is sensitive to hyperparameter tuning and may overfit on "
        "small datasets (n < 200 materials).",
        "Training time scales with n_estimators × n_samples; large datasets require "
        "careful resource management.",
    ],
    "gradient_boosting_classifier": [
        "Probability estimates from Gradient Boosting are not calibrated by default. "
        "Do not interpret predicted probabilities as well-calibrated uncertainties.",
    ],
    "mlp_regressor": [
        "Neural network regressors (MLP) require careful scaling and are sensitive to "
        "random initialization. Fix the random seed for reproducibility.",
        "Convergence is not guaranteed; monitor the loss curve and use early stopping.",
        "MLP models do not provide feature importance natively — use permutation "
        "importance or SHAP for interpretability.",
    ],
    "mlp_classifier": [
        "MLP classifiers do not natively produce calibrated probabilities. "
        "Confidence scores should not be used for risk-critical decisions without "
        "post-hoc calibration.",
    ],
    "svr": [
        "SVR with RBF kernel is computationally expensive for n > 10 000 samples.",
        "Kernel choice and regularization parameter C have a large effect on "
        "performance; a grid search is recommended for production use.",
    ],
    "gaussian_process_regressor": [
        "Gaussian Process Regression scales as O(n³) in training samples and is "
        "only practical for n < 1000 materials.",
        "The kernel function encodes strong prior assumptions about the correlation "
        "structure of the data. The default RBF kernel may not be appropriate for "
        "all material property landscapes.",
        "Uncertainty estimates are only valid within the training domain.",
    ],
    "logistic_regression": [
        "Logistic regression assumes a linear decision boundary in feature space. "
        "Non-linear class boundaries require a non-linear model.",
    ],
}

_PROPERTY_LIMITATIONS: dict[str, list[str]] = {
    "energy_above_hull": [
        "energy_above_hull is computed relative to the convex hull of competing "
        "phases in the Materials Project database. A value of 0 eV/atom means "
        "the material is on the hull at 0 K, NOT that it is experimentally stable.",
        "DFT calculations use approximate exchange-correlation functionals (PBE, "
        "PBE+U). Errors of 0.05–0.1 eV/atom are typical, which is comparable to "
        "the stability threshold used for classification.",
        "Temperature and entropic effects are not included. A material with "
        "energy_above_hull = 0.05 eV/atom at 0 K may be stable at room temperature "
        "or may decompose readily — this requires additional simulation.",
        "Synthesis feasibility is NOT implied by a low energy_above_hull. Kinetic "
        "barriers, metastability, and synthesis conditions are not captured.",
    ],
    "formation_energy_per_atom": [
        "Formation energy is referenced to DFT total energies of elemental reference "
        "states, which themselves carry approximation errors.",
        "GGA-PBE systematically underestimates formation energies of transition metal "
        "oxides. PBE+U corrections are applied in Materials Project but introduce "
        "U-value dependence.",
        "Formation energy does not directly predict electrochemical voltage or capacity.",
    ],
    "band_gap": [
        "DFT-PBE systematically underestimates band gaps. The actual electronic gap "
        "of a material is typically 30–50% larger than the DFT-PBE value.",
        "A band gap of 0 eV in DFT does not always mean the material is truly metallic; "
        "it may be a DFT artifact. HSE06 or GW calculations are needed for accuracy.",
        "Band gap is a bulk property; surface and interfacial effects at electrode "
        "interfaces are not captured by this descriptor.",
    ],
    "is_stable": [
        "is_stable is derived from energy_above_hull using a configurable threshold "
        "(default: ≤ 0.05 eV/atom). This threshold is empirical.",
        "DFT approximation errors mean that some truly unstable materials may be "
        "misclassified as stable, and vice versa.",
        "A 'stable' label from this classifier is a screening criterion, not a "
        "substitute for experimental synthesis and characterisation.",
    ],
}

_GENERAL_PREDICTION_LIMITATIONS = [
    "All predictions are derived from DFT-computed training data. "
    "Agreement with experiment depends on the accuracy of the DFT approximation "
    "and the representativeness of the training set.",
    "Extrapolation to materials with chemical compositions not represented in "
    "the training set (out-of-domain) is unreliable. Check the OOD flag.",
    "Model predictions are point estimates. Uncertainty quantification is only "
    "available for Gaussian Process models and, approximately, via prediction "
    "variance from Random Forests.",
    "This platform is designed for computational screening, not for production "
    "material recommendation. All high-priority candidates must be validated "
    "experimentally before any application.",
]


class ScientificLimitationsService:
    """
    Returns curated scientific limitation warnings for display in reports
    and the UI.  All text is static — no generative AI.
    """

    def get_limitations_for_descriptor_type(
        self, descriptor_type: str
    ) -> list[str]:
        """
        Return limitations for the given descriptor type.

        Args:
            descriptor_type: "compositional", "structural", or "combined".
        """
        key = descriptor_type.lower()
        return _DESCRIPTOR_LIMITATIONS.get(key, [
            f"No specific limitations catalogued for descriptor type '{descriptor_type}'."
        ])

    def get_limitations_for_model_type(self, model_type: str) -> list[str]:
        """
        Return limitations for the given model type string.

        Args:
            model_type: One of the ModelType enum values (e.g. "random_forest_regressor").
        """
        key = model_type.lower().replace("-", "_")
        general = [
            "Machine learning models trained on DFT data inherit all DFT approximation "
            "errors. Predictions cannot be more accurate than the training labels."
        ]
        specific = _MODEL_LIMITATIONS.get(key, [
            f"No specific limitations catalogued for model type '{model_type}'."
        ])
        return general + specific

    def get_limitations_for_target_property(self, target_property: str) -> list[str]:
        """
        Return known limitations for a DFT target property.

        Args:
            target_property: e.g. "energy_above_hull", "band_gap".
        """
        return _PROPERTY_LIMITATIONS.get(target_property, [
            f"No specific limitations catalogued for property '{target_property}'."
        ])

    def get_general_prediction_limitations(self) -> list[str]:
        """Return general caveats that apply to all ML predictions in this system."""
        return _GENERAL_PREDICTION_LIMITATIONS

    def get_full_limitations_for_prediction(
        self,
        model_type: str,
        target_property: str,
        descriptor_type: str,
        is_out_of_domain: bool = False,
        is_uncalibrated: bool = True,
    ) -> list[str]:
        """
        Compose the full set of limitations relevant to a specific prediction.

        Args:
            model_type:       ML model used.
            target_property:  Property predicted.
            descriptor_type:  Descriptor set used for features.
            is_out_of_domain: Whether the prediction was flagged as OOD.
            is_uncalibrated:  Whether the model confidence is not calibrated.

        Returns:
            Deduplicated, ordered list of limitation strings.
        """
        warnings: list[str] = []
        warnings.extend(self.get_general_prediction_limitations())
        warnings.extend(self.get_limitations_for_model_type(model_type))
        warnings.extend(self.get_limitations_for_target_property(target_property))
        warnings.extend(self.get_limitations_for_descriptor_type(descriptor_type))

        if is_out_of_domain:
            warnings.insert(
                0,
                "WARNING: This material is outside the applicability domain of the "
                "training set. The prediction reliability is significantly reduced.",
            )
        if is_uncalibrated:
            warnings.append(
                "Confidence scores reported by this model have not been post-hoc "
                "calibrated. They should not be interpreted as probabilities."
            )

        # Deduplicate while preserving order
        seen: set[str] = set()
        unique: list[str] = []
        for w in warnings:
            if w not in seen:
                seen.add(w)
                unique.append(w)
        return unique
